module.exports = {
    content: [
        "./test.html", // ⬅️ tambahkan ini
        "./views/**/*.ejs",
        "./app/**/*.js",
        "./public/**/*.html"
    ],
    safelist: [
        'btn', 'btn-primary', 'btn-secondary', 'btn-accent', 'btn-neutral', 'btn-ghost', 'btn-outline',
        'btn-sm', 'btn-lg', 'btn-xs', 'btn-circle',
        'text-4xl', 'text-green-600', 'text-primary', 'text-secondary', 'text-accent',
        'card', 'card-body', 'card-title', 'card-actions',
        'navbar', 'navbar-start', 'navbar-center', 'navbar-end',
        'menu', 'dropdown', 'dropdown-content',
        'alert', 'alert-info', 'alert-success', 'alert-warning', 'alert-error',
        'badge', 'badge-primary', 'badge-secondary', 'badge-accent', 'badge-success', 'badge-error',
        'hero', 'hero-content',
        'loading', 'loading-spinner',
        'stats', 'stat', 'stat-title', 'stat-value', 'stat-desc', 'stat-figure',
        'input', 'input-bordered', 'input-group',
        'form-control', 'label', 'label-text', 'label-text-alt',
        'mockup-code', 'divider', 'footer', 'footer-center',
        'collapse', 'collapse-arrow', 'collapse-title', 'collapse-content'
    ],
    theme: {
        extend: {},
    },
    plugins: [require("daisyui")],
    daisyui: {
        themes: [
            "light",
            "dark",
            "cupcake",
            "bumblebee",
            "emerald",
            "corporate",
            "synthwave",
            "retro",
            "cyberpunk",
            "valentine",
            "halloween",
            "garden",
            "forest",
            "aqua",
            "lofi",
            "pastel",
            "fantasy",
            "wireframe",
            "black",
            "luxury",
            "dracula",
            "cmyk",
            "autumn",
            "business",
            "acid",
            "lemonade",
            "night",
            "coffee",
            "winter"
        ],
        darkTheme: "dark",
        base: true,
        styled: true,
        utils: true,
        prefix: "",
        logs: true,
        themeRoot: ":root",
    },
}